#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = xconfig_helloWorld
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/utils.js:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/utils.js
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/xdc.tci:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/xdc.tci
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/template.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/template.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/om2.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/om2.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/xmlgen.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/xmlgen.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/xmlgen2.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/xmlgen2.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/Warnings.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/Warnings.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/IPackage.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/IPackage.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/package.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/package.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/services/global/Clock.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/services/global/Clock.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/services/global/Trace.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/services/global/Trace.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/bld.js:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/bld.js
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/BuildEnvironment.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/PackageContents.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/PackageContents.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/_gen.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/_gen.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Library.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Library.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Executable.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Executable.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Repository.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Repository.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Configuration.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Configuration.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Script.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Script.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Manifest.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Manifest.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Utils.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/Utils.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/ITarget.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/ITarget.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/ITarget2.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/ITarget2.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/ITarget3.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/ITarget3.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/ITargetFilter.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/package.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/bld/package.xs
package.mak: config.bld
C:/TI/bios_6_40_01_15/packages/ti/targets/ITarget.xs:
package.mak: C:/TI/bios_6_40_01_15/packages/ti/targets/ITarget.xs
C:/TI/bios_6_40_01_15/packages/ti/targets/C28_large.xs:
package.mak: C:/TI/bios_6_40_01_15/packages/ti/targets/C28_large.xs
C:/TI/bios_6_40_01_15/packages/ti/targets/C28_float.xs:
package.mak: C:/TI/bios_6_40_01_15/packages/ti/targets/C28_float.xs
C:/TI/bios_6_40_01_15/packages/ti/targets/package.xs:
package.mak: C:/TI/bios_6_40_01_15/packages/ti/targets/package.xs
C:/TI/bios_6_40_01_15/packages/ti/targets/elf/ITarget.xs:
package.mak: C:/TI/bios_6_40_01_15/packages/ti/targets/elf/ITarget.xs
C:/TI/bios_6_40_01_15/packages/ti/targets/elf/package.xs:
package.mak: C:/TI/bios_6_40_01_15/packages/ti/targets/elf/package.xs
package.mak: package.bld
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/services/io/File.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/services/io/File.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/services/io/package.xs:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/services/io/package.xs
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/CCS6/xdctools_3_30_01_25_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

ti.targets.elf.C66.rootDir ?= C:/CCS6/ccsv6/tools/compiler/c6000_7.4.8
ti.targets.elf.packageBase ?= C:/TI/bios_6_40_01_15/packages/ti/targets/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe66
.PHONY: all,e66 .dlls,e66 .executables,e66 test,e66
all,e66: .executables,e66
.executables,e66: .libraries,e66
.executables,e66: .dlls,e66
.dlls,e66: .libraries,e66
.libraries,e66: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e66
	@$(ECHO) xdc .executables,e66
	@$(ECHO) xdc .libraries,e66
	@$(ECHO) xdc .dlls,e66


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_xconfig_helloWorld.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package xconfig_helloWorld" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,e66 .dlls: helloWorld.pe66

-include package/cfg/helloWorld_pe66.mak
-include package/cfg/helloWorld_pe66.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/helloWorld_pe66.dep
endif
helloWorld.pe66: package/cfg/helloWorld_pe66.xdl
	@


ifeq (,$(wildcard .libraries,e66))
helloWorld.pe66 package/cfg/helloWorld_pe66.c: .libraries,e66
endif

package/cfg/helloWorld_pe66.c package/cfg/helloWorld_pe66.h package/cfg/helloWorld_pe66.xdl: override _PROG_NAME := helloWorld.xe66
package/cfg/helloWorld_pe66.c: package/cfg/helloWorld_pe66.cfg

clean:: clean,e66
	-$(RM) package/cfg/helloWorld_pe66.cfg
	-$(RM) package/cfg/helloWorld_pe66.dep
	-$(RM) package/cfg/helloWorld_pe66.c
	-$(RM) package/cfg/helloWorld_pe66.xdc.inc

clean,e66::
	-$(RM) helloWorld.pe66
.executables,e66 .executables: helloWorld.xe66

helloWorld.xe66: |helloWorld.pe66

-include package/cfg/helloWorld.xe66.mak
helloWorld.xe66: package/cfg/helloWorld_pe66.oe66 
	$(RM) $@
	@$(MSG) lnke66 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.elf.C66.rootDir)/bin/lnk6x -w -q -u _c_int00 -fs $(XDCCFGDIR)$(dir $@).  -q -o $@ package/cfg/helloWorld_pe66.oe66   package/cfg/helloWorld_pe66.xdl --abi=eabi -c -m $(XDCCFGDIR)/$@.map -l $(ti.targets.elf.C66.rootDir)/lib/libc.a
	
helloWorld.xe66: export C_DIR=
helloWorld.xe66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/;$(PATH)
helloWorld.xe66: Path:=$(ti.targets.elf.C66.rootDir)/bin/;$(PATH)

helloWorld.test test,e66 test: helloWorld.xe66.test

helloWorld.xe66.test:: helloWorld.xe66
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 helloWorld.xe66.test
else
	@$(MSG) running $<  ...
	$(call EXEC.helloWorld.xe66, ) 
endif

clean,e66::
	-$(RM) .tmp,helloWorld.xe66,0,*


clean:: clean,e66

clean,e66::
	-$(RM) helloWorld.xe66
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
helloWorld_pe66.oe66,copy : package/cfg/helloWorld_pe66.oe66
helloWorld_pe66.se66,copy : package/cfg/helloWorld_pe66.se66

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,xconfig_helloWorld
xconfig_helloWorld.tar: package/package.bld.xml
xconfig_helloWorld.tar: package/build.cfg
xconfig_helloWorld.tar: package/package.xdc.inc
ifeq (,$(MK_NOGENDEPS))
-include package/rel/xconfig_helloWorld.tar.dep
endif
package/rel/xconfig_helloWorld/xconfig_helloWorld/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

xconfig_helloWorld.tar: package/rel/xconfig_helloWorld.xdc.inc package/rel/xconfig_helloWorld/xconfig_helloWorld/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/xconfig_helloWorld.xdc.inc,package/rel/xconfig_helloWorld.tar.dep)


release release,xconfig_helloWorld: all xconfig_helloWorld.tar
clean:: .clean
	-$(RM) xconfig_helloWorld.tar
	-$(RM) package/rel/xconfig_helloWorld.xdc.inc
	-$(RM) package/rel/xconfig_helloWorld.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
